CREATE DATABASE estoqueCentral;
USE estoqueCentral;

CREATE TABLE TipoTransacao(
	Id		INT PRIMARY KEY NOT NULL,
	nome	VARCHAR(50) NOT NULL,
);

CREATE TABLE Prestador(
	Id				INT PRIMARY KEY IDENTITY,
	nome			VARCHAR(50) NOT NULL,
	cnpj			VARCHAR(25) NOT NULL,
	razaoSocial		VARCHAR(100) NOT NULL,
	endereco		VARCHAR(150) NOT NULL,
	telefone		VARCHAR(13) NOT NULL,
	email			VARCHAR(100) NOT NULL,
	contato			VARCHAR(100) NOT NULL
);

CREATE TABLE Armazem(
	ID				INT PRIMARY KEY IDENTITY NOT NULL,
	nome			VARCHAR(50) NOT NULL,
	endereco		VARCHAR(150) NOT NULL,
	responsavel		VARCHAR(50) NOT NULL
);

CREATE TABLE Categoria(
	id		INT PRIMARY KEY IDENTITY NOT NULL,
	nome	VARCHAR(50) NOT NULL
);

CREATE TABLE Item(
	ID						INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	nome					VARCHAR(50) NOT NULL,
	numeroLoteRequerido		BIT NULL,
	quantidadeMinima		INT NULL,
	FonercedorID			INT FOREIGN KEY REFERENCES Prestador(Id) NULL,
	CategoriaID				INT FOREIGN KEY REFERENCES Categoria(id) NULL,
	LocalID					INT NULL,
);

CREATE TABLE Pedido(
	ID					INT PRIMARY KEY IDENTITY NOT NULL,
	tipoTransacaoID		INT FOREIGN KEY REFERENCES TipoTransacao(Id) NOT NULL,
	transportadoraID	INT FOREIGN KEY REFERENCES Prestador(Id) NULL, 
	lojaID				INT FOREIGN KEY REFERENCES Prestador(Id) NULL,
	armazemOrigemID		INT FOREIGN KEY REFERENCES Armazem(ID) NULL,
	armazemDestinoID	INT FOREIGN KEY REFERENCES Armazem(ID) NULL,
	dataPedido			DATE NOT NULL,
	dataEntrega			DATE NULL
);

CREATE TABLE ItemPedido(
	ID			INT PRIMARY KEY IDENTITY NOT NULL,
	pedidoID	INT	FOREIGN KEY REFERENCES Pedido(ID) NOT NULL,
	itemID		INT FOREIGN KEY REFERENCES Item(Id) NOT NULL,
	numeroLote	VARCHAR(50) NULL,
	quantidade	DECIMAL(18,2) NOT NULL
);

USE MASTER
GO

DROP DATABASE estoqueCentral
GO